# Generated by Django 5.0.1 on 2024-01-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Время')),
                ('action', models.CharField(blank=True, choices=[('study', 'Изучать новое'), ('develop', 'Развивать личные и профессиональные навыки'), ('sport', 'Заниматься спортом')], max_length=200, null=True, verbose_name='Действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('twice a week', 'Два раза в неделю'), ('three times a week', 'Три раза в неделю'), ('weekly', 'Раз в неделю')], max_length=50, null=True, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('lead_time', models.IntegerField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('habits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
